### ISSUE TITLE
A few comments about the initial implementation

### ISSUE THREAD

**Issue by code-overseer** [DaedraKyne/Cpp-List#1]
### 1. Add `const` to the read-only function members
For example:
```cplusplus
bool Contains(std::string) const;
```
It lets the reader know that the function doesn't modify the object state, allows for potential optimization opportunities to the compiler, and will also have the compiler raise an error if you attempt to modify the class state in a `const` function member (see [here](https://godbolt.org/z/s34356YYK)).

### 2. C++ is copy by value, just like C, i.e.

```cplusplus
int foo(std::string str);

std::string str = "Some very long string here";
func(str); //  This line will make a copy of the string to pass into the function
```
Make the relevant function parameters const reference:
```
bool Contains(const std::string&) const;
int IndexOf(const std::string&) const;
bool Remove(const std::string&) const;
```

### 3. Return const reference for `Get`:

```cplusplus
const std::string& Get(int index) const;
```
This ensures that when you return `data[index]`, no copy of the string is made, but will return the reference to the indexed string instead

### 4. Copy constructors and assignment operators:

If you have a class that calls new/delete, you will typically need to define a custom copy constructor and assignment operator. C++'s default copy constructor and copy assignment operator will copy all the members, but since one of your members is just a pointer to some memory, the default copy will blindly copy the pointer.
```
List_string(const List_string& other); // copy ctor
List_string& operator=(const List_string& other); // copy assignment
```

Without them, you will segfault in the following:
```cplusplus

List_string first;
{
    List_string second;
    second.Add("hello world");
    first = second;    
}

cout << first.Get(0); // <- segfaults
```
What's happening is as follows: 
    1. create `first`
    2. create `second` and add a string in a new scope
    3. assign `second` to `first` which by default assigns the pointer and two integers
    4. `second` goes out of scope (because it was initialized within the brace) and gets destroyed
    5. The copied pointer to the deallocated memory is still in `first`
    6. You try to access deallocated memory

**Comment by DaedraKyne** [comment]
> 3. Return const reference for Get:
> const std::string& Get(int index) const;
> This ensures that when you return data[index], no copy of the string is made, but will return the reference to the indexed string instead

Since the List itself contains value copies of the original data, it makes sense for the get method to return a copy of the stored data. 
It would be interesting, however, to store references of all data as opposed to storing value copies

**Comment by code-overseer** [comment]
> Since the List itself contains value copies of the original data, it makes sense for the get method to return a copy of the stored data.
It forces a considerable penalty (copying the string) on examining values in the list. Returning a reference provides more flexibility, if the user wants a copy, they can use `std::string copy = list.Get(0);` 

> It would be interesting, however, to store references of all data as opposed to storing value copies
There's a `string_view` class in C++17 which is effectively a non-owning reference to a string, it just contains a pointer and a size. You generally don't put that in a container unless you are 100% sure no one will cause a segfault.

**Comment by code-overseer** [comment]
## More comments

### 1. Not everything needs to be passed by reference

Fundamental types like integers, floats, and pointers, can be passed by value. The compiler will handle it. In the best case, you'll get a performance boost as you won't need additional indirection to access the data through the reference, worst case the extra cost of copying is negligible. 

Generally my checklist for function parameter types:
* If it's a fundamental type or smaller than 32 bytes[^1] with no internal allocation => pass by value
* If the data will be copied inside the function => pass by value, so that the function caller has the option to move construct instead of copying
* If the data is move-only => pass by value if it's a public API[^2] (functions called across modules/DLLs[^3]), by rvalue reference if it's an internal API (only within the DLL)
* Function is public API and parameter is a string => use `std::string_view`
* Otherwise, pass by rvalue or lvalue reference depending on necessity

[^1]:  This is just my personal heuristic, based on the fact that modern x86-64 CPUs can copy 32 bytes of data in a single instruction if it's aligned properly
[^2]: By public API, I mean functions that are exported and are visible from outside of a dynamic library
[^3]:  This is only in Unreal, it's actually quite difficult to distribute DLLs in C++ unless you're absolutely sure of the toolchains being used.

### 2. Define copy assignment formally

Typically, best practice will be to define copy assignment with the following signature:
```cplusplus
List_String& List_String::operator=(const List_String& other)
```
It's easier for other programmers to recognize and it's also the signature that the compiler recognizes as the class's copy-assignment operator. The compiler has special treatments for default constructors, copy constructors, destructors, copy assignment operators, move constructors, and move assignment operators.

You may have a private assign function internally if that makes things easier.

For example:
```cplusplus
private:
List_String& List_String::assign(List_String other);
public:
List_String& List_String::operator=(const List_String& other) { return assign(other); }
```
The third operator is the move assignment operator. (You should define a move assignment and move constructor for the class as well)

### 3. Learn about move semantics and define the move constructor and move assignment operator

This is in my opinion one of the more important features of C++ that anyone coming from another language should learn about. Think of it like an ownership transfer. Copying creates a new instance that owns a new copy of the original instance's resource, moving implies that you are transferring the ownership of the resource to another instance and invalidating the original instance. It's meant to work as an optimization of copy.

### 4. Define iterators

In my opinion, this is probably the most annoying thing to do when defining custom containers. It's very boilerplate-y and I don't really know a way to speed up doing this. So I would say, this is useful to know but we can skip it if you want, it's up to you. 

You typically won't have to define this unless you're writing a general-purpose container; I've only written 2 general-purpose containers in my 4 years of improbable, and out of the 2, I've only defined a bare-bones iterator class for 1 of them.

I found [this](https://home.csulb.edu/~pnguyen/cecs282/lecnotes/iterators.pdf) from a quick Google search. 

Standard containers will typically have the following functions:
```cplusplus
iterator begin();
const_iterator begin() const;
const_iterator cbegin() const;
iterator end();
const_iterator end() const;
const_iterator cend() const;
```
Where `iterator` and `const_iterator` are classes you define.

If done correctly, the following should compile:

```cplusplus
for (std::string& str : str_list) {
    str += "[processed]";
}

for (const std::string& str : str_list) {
    assert(str.find("[processed]") != std::string::npos);
}
```

### Nits/Other useful info:
* You typically only need the `using std::swap` when you're in generics, in this case, you know all the types, so all it does is reduce the effort in typing `std::`.
* There's a std function for copying ranges that you can use:
```cplusplus
#include <algorithm>

data = new std::string[capacity];
std::copy(other.data, other.data + count, data); // copies everything in (other.data, other.data + count] into data
```
* You can keep the exceptions in, but just be aware exceptions aren't something used in the games industry; Unreal doesn't use them at all. There are very rare cases where it's used, but you won't really see them very often due to performance costs and the fact that in games, there really isn't a state you can recover to if an exception is thrown. Generally, we'll have a debug/test build that has assertion-like macros turned on and use those instead of throwing exceptions. On a shipping build, those assertion macros are turned off because those states should never be encountered on a shipping build after extensive testing and debugging by QA or engineers.

**Comment by code-overseer** [comment]
### 1. Memory leak
```cplusplus
bool List_String::RemoveAt(int index) {
	if (index < 0) return false;
	if (index >= count) return false;
	//allowed setting: index = [0, count-1], count > 0 (data is initialized)

	memmove(data + index, data + index + 1, (count - index - 1) * sizeof(std::string)); //shallow shuffle left
	count--;
	return true;
}
```
You haven't deleted the memory owned by the string instance you're removing. You can use [std::move in algorithm](https://en.cppreference.com/w/cpp/algorithm/move) instead.
Also, using `memmove` is actually undefined behavior for `std::string`.

### 2. Unnecessary CreateDeepCopy overload
```cplusplus
std::string* CreateDeepCopy(std::string* data, size_t data_size);
```
This seems unnecessary. I think you should be using `CreateDeepCopy(data, capacity, count)` in the copy constructor.

### 3. Should probably add the const iterators as well
```cplusplus
    const std::string* begin() const;
    const std::string* end() const;
    const std::string* cbegin() const;
    const std::string* cend() const;
```

### 4. You don't have to observe the result of every operation:
e.g.
```
bool Capacity(int value);
```
It's a bit unnecessary to observe the result of this. You'll get one of these cases usually:
* It bloats the users' code, as they will be tempted to always check for success 
* It's unnecessary because users will always provide a value greater than the current capacity. 

It's better to just return void and document in the header, that if `value` is less than the current capacity, nothing happens.

Also doesn't seem like you need the boolean return for `Add`.

## Optimization opportunities:

### 1. Add
This is what you have currently:
```cplusplus
bool Add(const std::string& new_val);
```

Consider these cases:
* You receive a `std::string` instance from an external source, e.g. external library, code written by a different team, etc. You just want to add the string to the list but no longer need the original string after that. In your current implementation, the original string needs to be copied and after the copy is added to the list, the original string is deallocated. Can we avoid the copy as well as the cost of deallocating the original string?
* Suppose I have a list of string literals I need to add to the List, I call the following:
```cplusplus
list.Add("Some very very long string literal 1");
list.Add("Some very very long string literal 2");
list.Add("Some very very long string literal 3");
```
In the code above, a temporary string will be constructed for each of those string literals. Each of those temporary strings are then copied to the list and then the temporary strings are destroyed. Can we avoid constructing and destroying the temporary strings?

### 2. Skipping unnecessary object construction
Currently, you are using the `new` operator to allocate the string array
```cplusplus
data = new std::string[N];
```
That operator will allocate enough memory for N string instances but it will also call the default constructor for all N strings. Can we improve upon this? i.e. only construct elements when we need to.

Clue: Use `std::allocator<std::string>` and placement new (or other alternatives if you can find them)

After implementing the above, can the `Add` function be improved such that string instances are constructed directly in the memory location of the newly added element, instead of needing to construct intermediate instances every time.

Clue: look up perfect forwarding
